import {MigrationInterface, QueryRunner} from 'typeorm'

export class MockData1642721080885 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Day of the Jackal, The', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', '2021-04-15T22:20:59Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Android', 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla', '2021-09-04T01:45:20Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Last Train Home', 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at', '2021-02-24T12:50:19Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Oh Happy Day', 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem', '2021-03-22T20:07:21Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Andy Hardy Meets Debutante', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet', '2021-01-21T07:24:56Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Take My Eyes (Te doy mis ojos)', 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', '2021-06-26T18:37:54Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Hot Lead and Cold Feet', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor', '2021-10-15T01:05:40Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Escapist, The', 'morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', '2021-06-04T03:24:53Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('The Strength of Water', 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', '2021-09-20T05:45:29Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Once in the Life', 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non', '2021-08-06T22:22:35Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('White Zombie', 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla', '2021-10-10T12:53:30Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('One Piece Film: Strong World', 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis', '2021-04-03T22:28:38Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Phantom of the Opera, The', 'sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem', '2021-05-08T04:59:12Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Looking for Maria Sanchez', 'in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae', '2021-01-24T03:38:12Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Sergio', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc', '2021-12-01T02:59:48Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Dear Mr. Watterson', 'sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut', '2021-02-01T01:53:49Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Dragon Ball Z: Cooler''s Revenge (Doragon bôru Z 5: Tobikkiri no saikyô tai saikyô)', 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', '2021-11-25T05:45:20Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Boy Who Could Fly, The', 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', '2021-08-15T10:10:58Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Usual Suspects, The', 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', '2021-04-01T14:03:58Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Orpheus (Orphée)', 'odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque', '2021-08-14T11:27:09Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Blackwoods', 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed', '2021-10-04T23:18:50Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Crazy/Beautiful', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet', '2021-10-31T12:13:40Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Dead End Drive-In', 'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', '2021-05-24T08:14:11Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Hoffa', 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', '2021-10-01T13:39:08Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Blind', 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede', '2021-05-28T08:48:51Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('The Girls', 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', '2021-05-15T05:47:14Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Eclipse, The', 'purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at', '2021-03-10T06:47:15Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Parasites, Les', 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', '2021-09-15T23:51:00Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Charlie Chan in Dangerous Money', 'vel sem sed sagittis nam congue risus semper porta volutpat quam', '2021-08-23T13:16:07Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Tenchi: The Samurai Astronomer', 'pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in', '2021-09-03T20:42:08Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('That Sugar Film', 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', '2021-10-20T18:00:15Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Cops and Robbersons', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque', '2021-09-09T18:11:32Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('The Amazing Dr. Clitterhouse', 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien', '2021-07-05T03:23:27Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Son of Babylon (Syn Babilonu)', 'elit proin risus praesent lectus vestibulum quam sapien varius ut', '2021-07-30T11:49:25Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Whole Wide World, The', 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum', '2021-08-17T20:10:09Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Château, The', 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', '2021-09-06T11:01:58Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('X: The Unknown', 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', '2021-04-17T14:26:52Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Animal Factory', 'semper est quam pharetra magna ac consequat metus sapien ut', '2021-11-15T16:04:51Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Texas Rangers', 'tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis', '2021-11-18T20:08:47Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Narrow Margin', 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est', '2021-11-11T01:09:37Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Abbott and Costello Go to Mars', 'id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo', '2021-05-25T05:50:22Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Wuthering Heights', 'non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar', '2021-06-02T06:52:42Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Crane World (Mundo grúa)', 'eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', '2021-02-09T20:52:38Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Candyman 3: Day of the Dead', 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare', '2021-10-19T05:16:38Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Dogs of War, The', 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci', '2021-08-16T06:08:48Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Sh! The Octopus', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit', '2021-04-18T09:02:38Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('AM1200', 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci', '2021-10-05T14:25:16Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Boys & Girl from County Clare, The (a.k.a. The Boys from County Clare)', 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut', '2022-01-17T11:08:49Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Sublime', 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit', '2021-08-16T02:32:29Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Borrowed Time', 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', '2021-02-14T15:32:56Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Escape from Planet Earth', 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu', '2021-10-07T18:36:44Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Gathering, The', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor', '2021-08-24T02:31:00Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Arthur 2: On the Rocks', 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa', '2021-07-02T00:50:37Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Devil and Daniel Webster, The (All That Money Can Buy)', 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', '2021-02-02T16:38:49Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Paradise', 'rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non', '2021-04-17T06:03:33Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Beginner''s Guide to Endings, A', 'eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae', '2021-06-23T20:42:53Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Rogue', 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi', '2021-03-06T23:45:59Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Mammoth (Mammut)', 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', '2021-04-22T06:30:23Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Meet Bill', 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat', '2021-08-27T18:40:52Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Black Watch, The', 'elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien', '2021-02-02T23:36:30Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Scandal Sheet', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', '2021-05-03T04:29:52Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Doom', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices', '2021-04-11T17:33:45Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Stendhal Syndrome, The (Sindrome di Stendhal, La)', 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi', '2021-06-29T01:51:31Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Raajneeti', 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam', '2021-12-29T22:34:37Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Back in Business', 'dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien', '2021-06-04T23:31:47Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('So Long Letty', 'nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', '2022-01-16T02:56:36Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Jasminum', 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum', '2021-03-31T08:22:00Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Sheep Eaters (Lampaansyöjät)', 'nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros', '2021-09-01T03:30:27Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Patton Oswalt: Finest Hour', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', '2021-02-11T13:48:46Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Meu Passado Me Condena: O Filme', 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis', '2021-03-01T07:44:49Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Ear, The (Ucho)', 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio', '2021-05-15T17:01:06Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Scusa ma ti chiamo amore', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', '2021-12-09T14:54:07Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Boogeyman', 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', '2021-11-22T07:52:33Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('The Golden Voyage of Sinbad', 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce', '2021-04-14T11:58:42Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Space Chimps', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris', '2021-09-09T18:22:27Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Ice Poison', 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', '2021-12-06T23:05:35Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Gaucho, The', 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', '2021-12-27T08:09:45Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Sleuth', 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', '2021-08-12T20:18:19Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Beyond the Time Barrier', 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', '2021-04-14T13:59:56Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Just Imagine', 'egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus', '2021-04-14T07:07:26Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Kings of Mykonos, The', 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere', '2021-07-28T05:33:03Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Crime of Monsieur Lange, The (Le crime de Monsieur Lange)', 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante', '2021-09-08T07:09:13Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Taste of Tea, The (Cha no aji)', 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus', '2021-08-16T23:14:26Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Big Trouble in Little China', 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', '2021-07-22T22:05:35Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Hush', 'in est risus auctor sed tristique in tempus sit amet sem fusce consequat', '2021-04-22T02:18:29Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Patriotism (Yûkoku)', 'ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam', '2021-10-08T08:34:32Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Legend of Hell House, The', 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede', '2021-10-12T02:53:21Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('The Miracle of Our Lady of Fatima', 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', '2021-05-11T16:18:39Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Gemini (Sôseiji)', 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et', '2021-02-08T17:43:13Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Red Beard (Akahige)', 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at', '2021-01-31T01:14:21Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('I Want to Live!', 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', '2021-08-10T04:07:09Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('My Way (Mai Wei)', 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', '2021-10-26T17:57:30Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Room in Rome (Habitación en Roma)', 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam', '2021-09-23T01:06:17Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Cloak & Dagger', 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', '2021-05-16T20:34:39Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Where the Rivers Flow North', 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', '2021-06-13T20:59:40Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Ace Ventura: Pet Detective', 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', '2021-10-18T21:32:48Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Kapitalism: Our Improved Formula (Kapitalism - Reteta noastra secreta)', 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat', '2021-09-15T03:25:04Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Red Riding: 1983', 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', '2021-08-25T22:54:58Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Dangerous Liaisons', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper', '2021-04-03T17:00:28Z', 1, 0);
      insert into "post" (title, content, "createdAt", "creatorId", "voteCount") values ('Eyjafjallajökull', 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', '2021-03-20T19:56:23Z', 1, 0);
      `  
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'delete from "post" where true'
    )
  }

}
